spring:
  application:
    name: learn-graphql-spring-boot

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 5
    exception-handlers-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
voyager:
  enabled: true
  mapping: /voyager
  endpoint: /graphql
