spring:
  application:
    name: learn-graphql-spring-boot
  servlet:
    multipart:
      max-file-size: 2MB

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
    tracingEnabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
voyager:
  enabled: true
  mapping: /voyager
  endpoint: /graphql
